---
# See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
author: Cogni AI OU
branding:
  color: blue
  icon: cpu
description: Runs OpenCode Agent
inputs:
  agent:
    description: Agent to use.
    required: false
  model:
    default: opencode/gemini-3-flash
    description: Model to use for OpenCode.
    required: false
  mentions:
    default: /oc,/opencode,/review  # Note: Do not change default triggers.
    description: Comma-separated trigger mentions for OpenCode.
    required: false
  opencode-api-key:
    description: API key for OpenCode.
    required: true
  permissions:
    description: Permissions configuration
    required: false
  prompt:
    default: ''
    description: Prompt to pass to the agent.
    required: false
name: OpenCode Agent
outputs:
  prompt:
    description: The resolved prompt sent to the agent.
    value: ${{ inputs.prompt }}
  response:
    description: The response from the agent.
    value: ${{ steps.opencode.outputs.response }}
runs:
  using: composite
  steps:
    - name: Run opencode
      id: opencode
      uses: anomalyco/opencode/github@v1.4.3
      env:
        OPENCODE_API_KEY: ${{ inputs.opencode-api-key }}
        OPENCODE_PERMISSION: ${{ inputs.permissions || env.OPENCODE_PERMISSION }}
      with:
        agent: ${{ inputs.agent }}
        mentions: ${{ inputs.mentions }}
        model: ${{ inputs.model }}
        prompt: ${{ inputs.prompt }}
        use_github_token: false
