---
name: Action
run-name: "Agent on #${{ github.event.issue.number || github.event.pull_request.number || github.event.discussion.number || github.run_id }}"
on:
  pull_request:
    paths-ignore:
      - '*.md'
jobs:
  test:
    if: github.event.sender.type != 'Bot'
    name: Run Action
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - name: Run Action
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          opencode-api-key: ${{ secrets.OPENCODE_API_KEY }}
          prompt: ${{ github.event.head_commit.message || github.event.pull_request.title }}
      - name: Print logs
        if: cancelled() || failure()
        run: grep -v INFO ~/.local/share/opencode/log/* || true
